# -*- coding: utf-8 -*-
"""RAG_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfB7pRo-5psFigNnQLZWPHZHu-FLosMN
"""

!pip install -qU \
langchain \
langchain-community \
langchain-core \
langchain-text-splitters \
langchain-huggingface \
transformers \
sentence-transformers \
faiss-cpu \
pypdf \
accelerate

from google.colab import files
uploaded = files.upload()

!pip install pymupdf

from langchain_community.document_loaders import PyMuPDFLoader

pdf_path = "sample.pdf"
loader = PyMuPDFLoader(pdf_path)
documents = loader.load()

print("Pages loaded:", len(documents))
print(documents[0].page_content[:500])

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", ".", " ", ""]
)

docs = text_splitter.split_documents(documents)

print("Chunks created:", len(docs))
print(docs[0].page_content[:300])

import re

def clean_text(text):
    text = re.sub(r'\$.*?\$', '', text)
    text = re.sub(r'\\[a-zA-Z]+\{.*?\}', '', text)
    text = re.sub(r'[_^{}\\]', ' ', text)
    text = re.sub(r'(\w)\n(\w)', r'\1 \2', text)
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

for doc in documents:
    doc.page_content = clean_text(doc.page_content)

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=400,
    chunk_overlap=50,
    separators=["\n\n", "\n", ".", " ", ""]
)
docs = text_splitter.split_documents(documents)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

def generate_answer(prompt):
    inputs = tokenizer(prompt, return_tensors="pt",
                       truncation=True, max_length=512)
    outputs = model.generate(**inputs, max_new_tokens=200)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def ask_rag(question):
    retrieved_docs = retriever.invoke(question)
    context = " ".join([d.page_content for d in retrieved_docs])
    prompt = f"Answer the question based on the context.\nContext: {context[:1200]}\nQuestion: {question}\nAnswer:"
    return generate_answer(prompt)

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(docs, embeddings)

print("Vector DB created")

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-large"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_answer(prompt):
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True)
    outputs = model.generate(**inputs, max_new_tokens=256)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

!pip install groq

from groq import Groq

client = Groq(api_key="YOUR_GROQ_API_KEY_HERE")

def ask_rag(question):
    retrieved_docs = retriever.invoke(question)
    context = " ".join([d.page_content for d in retrieved_docs])

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant. Answer questions using only the provided context."
            },
            {
                "role": "user",
                "content": f"Context:\n{context[:3000]}\n\nQuestion: {question}\n\nAnswer:"
            }
        ]
    )
    return response.choices[0].message.content

query = "What is this document about?"
docs = retriever.invoke(query)

for i, doc in enumerate(docs):
    print(f"\n--- Chunk {i+1} ---\n")
    print(doc.page_content[:400])

!pip install gradio

print("ask_rag exists:", "ask_rag" in globals())

import gradio as gr

def chat_fn(message, history):
    return ask_rag(message)

demo = gr.ChatInterface(fn=chat_fn)
demo.launch(share=True)